# SPDX-License-Identifier: MulanPSL-2.0 OR Unlicense
[book]
title = "K4m7v2pz's Blog"
authors = ["k4m7v2pz"]
language = "zh"
src = "src"
description = "k4m7v2pz 的博客"

[output.html]
site-url = "https://k4m7v2pz.github.io/zh/"
edit-url-template = "https://github.com/k4m7v2pz/k4m7v2pz.github.io/edit/dev/book-zh/{path}"
git-repository-url = "https://github.com/k4m7v2pz/k4m7v2pz.github.io"
